//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARK.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".tts")]
        public string Synthesizer_Command {
            get {
                return ((string)(this["Synthesizer_Command"]));
            }
            set {
                this["Synthesizer_Command"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Synthesizer_Volume {
            get {
                return ((int)(this["Synthesizer_Volume"]));
            }
            set {
                this["Synthesizer_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Synthesizer_Rate {
            get {
                return ((int)(this["Synthesizer_Rate"]));
            }
            set {
                this["Synthesizer_Rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int Microphone_Buffer_Time {
            get {
                return ((int)(this["Microphone_Buffer_Time"]));
            }
            set {
                this["Microphone_Buffer_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Microphone_Volume {
            get {
                return ((int)(this["Microphone_Volume"]));
            }
            set {
                this["Microphone_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Media_Volume {
            get {
                return ((int)(this["Media_Volume"]));
            }
            set {
                this["Media_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Loopback_Volume {
            get {
                return ((int)(this["Loopback_Volume"]));
            }
            set {
                this["Loopback_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Standard_Volume {
            get {
                return ((int)(this["Standard_Volume"]));
            }
            set {
                this["Standard_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setup_Microphone_SelectedIndex {
            get {
                return ((int)(this["Setup_Microphone_SelectedIndex"]));
            }
            set {
                this["Setup_Microphone_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setup_Standard_Output_SelectedIndex {
            get {
                return ((int)(this["Setup_Standard_Output_SelectedIndex"]));
            }
            set {
                this["Setup_Standard_Output_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Setup_Loopback_Output_SelectedIndex {
            get {
                return ((int)(this["Setup_Loopback_Output_SelectedIndex"]));
            }
            set {
                this["Setup_Loopback_Output_SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Interface_Theme_Accent {
            get {
                return ((int)(this["Interface_Theme_Accent"]));
            }
            set {
                this["Interface_Theme_Accent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_SteamApps_Folder {
            get {
                return ((string)(this["Setup_SteamApps_Folder"]));
            }
            set {
                this["Setup_SteamApps_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setup_Audio_Watch_Folder {
            get {
                return ((string)(this["Setup_Audio_Watch_Folder"]));
            }
            set {
                this["Setup_Audio_Watch_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0.0")]
        public string SettingsVersion {
            get {
                return ((string)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
    }
}
